<Project>
    <PropertyGroup>
        <Version>2.0.4</Version>
        <PackageId>RoccoZero.$(MSBuildProjectName)</PackageId>
        <Authors>Nevermore;RoccoZero</Authors>
        <RepositoryUrl>https://github.com/RoccoZero/AsyncNavigation</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <PackageReadmeFile>readme.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/RoccoZero/AsyncNavigation</PackageProjectUrl>
        <Description>A lightweight asynchronous navigation framework based on Microsoft.Extensions.DependencyInjection</Description>
    </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\readme.md" Link="readme.md"  Pack="true" PackagePath=""/>
  </ItemGroup>
</Project>